### ISSUE TITLE
can not catch the error RemixApi failed with status 429

### ISSUE THREAD

**Issue by hejuntt1014** [erictik/midjourney-api#197]
### the code that reproduces this issue or a replay of the bug

Unhandled Rejection at: Promise {
 <rejected> Error: RemixApi failed with status 429
    at onmodal (/midjourney-api/src/midjourney.ts:307:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.onmodal (/midjourney-api/src/discord.ws.ts:548:23)

### Describe the bug

**Describe the bug**
can not catch RemixApi failed with status 429.

**Expected behavior**
Hope to catch this exception through try-catch. like
try{
  const Variation = await client.Variation({
  ....
}catch(err){
}

**Screenshots**
Unhandled Rejection at: Promise {
 <rejected> Error: RemixApi failed with status 429
    at onmodal (/midjourney-api/src/midjourney.ts:307:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.onmodal (/midjourney-api/src/discord.ws.ts:548:23)

### error log

Unhandled Rejection at: Promise {
 <rejected> Error: RemixApi failed with status 429
    at onmodal (/midjourney-api/src/midjourney.ts:307:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.onmodal (/midjourney-api/src/discord.ws.ts:548:23)

**Comment by zcpua** [comment]
Bug Report for Examples,please

**Comment by zcpua** [comment]
example: 
https://github.com/erictik/midjourney-api/blob/main/example/variation-ws.ts
