### ISSUE TITLE
Error: ImagineApi failed with status 400

### ISSUE THREAD

**Issue by CAPTAIN320** [erictik/midjourney-api#22]
Error: ImagineApi failed with status 400
    at Midjourney.Imagine (/Users/username/github/midjourney-api/src/midjourney.ts:24:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (/Users/username/github/midjourney-api/example/imagine.ts:17:15)

**Comment by raisen** [comment]
Do you have a paid Midjourney account? I'm getting the same error, but my subscription has expired. I didn't try to run this API while my subscription was still active.

**Comment by CAPTAIN320** [comment]
> Do you have a paid Midjourney account? I'm getting the same error, but my subscription has expired. I didn't try to run this API while my subscription was still active.

It works now! 
The problem was incorrect environment variables. 
I have a subscription.
Thanks for reminding me about the problem!
