### ISSUE TITLE
Error: ImagineApi failed with status 429

### ISSUE THREAD

**Issue by morganfuchs** [erictik/midjourney-api#235]
### the code that reproduces this issue or a replay of the bug

-

### Describe the bug

For the past 2 days, I've been getting random 429 errors. That's twice now that I've used several accounts to generate 1000-2000 images per day without any problem. 

I've added a proxy, added the apiInterval=10000 property, changed the serverID, refresh the salaiToken, tried on several accounts and I still get the error at some point. 

What criteria can generate this error? Has anyone ever had these errors?

### error log

["Error: ImagineApi failed with status 429\n    at Midjourney.Imagine (/app/node_modules/midjourney/libs/midjourney.js:69:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MidjourneyApiService.imagine (/app/dist/apps/f_midjourney/main.js:154:16)\n    at async Worker.processor [as processFn] (/app/dist/apps/f_midjourney/main.js:12932:48)\n    at async Worker.processJob (/app/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)\n    at async Worker.retryIfFailed (/app/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)"]

**Comment by jimmy0324** [comment]
+1  
and a bit hard to reproduce this issue. But I can see quite a few this errors from logs.

**Comment by jaoh1234** [comment]
i know it's been a while back but were you able to solve this?

**Comment by ideepankarsharma2003** [comment]
This happens when you make multiple requests using your exceeded quota of concurrent calls I guess
