### ISSUE TITLE
Error: ImagineApi failed with status 400

### ISSUE THREAD

**Issue by liuyongchun** [erictik/midjourney-api#51]
Error: ImagineApi failed with status 400
    at Midjourney.Imagine (d:\work\project\test\midjourney-api\src\midjourney.ts:46:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (d:\work\project\test\midjourney-api\example\imagine-ws.ts:20:15)

**Comment by zcpua** [comment]
check env

**Comment by bzm121** [comment]
@liuyongchun 之前参数都可以正常访问，昨天后，就报400错误。这个问题你解决了吗？

**Comment by artemptushkin** [comment]
any feedback? same issue

**Comment by lys623** [comment]
+1
