### ISSUE TITLE
Error: ImagineApi failed with status 500

### ISSUE THREAD

**Issue by liyanan666** [erictik/midjourney-api#60]
why report Error: ImagineApi failed with status 500

**Comment by manza7014** [comment]
+1

**Comment by manza7014** [comment]
`TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11404:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Midjourney.interactions (/Users/liyongfeng/develop/mcn/midjourney-api/src/midjourney.ts:79:24) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8377:28)
      at node:internal/deps/undici/undici:8335:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8366:13)
      at process.processImmediate (node:internal/timers:475:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
finished
Error: ImagineApi failed with status 500
    at Midjourney.Imagine (/Users/liyongfeng/develop/mcn/midjourney-api/src/midjourney.ts:46:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (/Users/liyongfeng/develop/mcn/midjourney-api/example/imagine-ws.ts:23:15)
liyongfengdeMacBook-Pro-2:midjourney-api liyongfeng$ `

**Comment by rictt** [comment]
same problem with fetch failed.

**Comment by dd123-a** [comment]
Has this problem been solved
