### ISSUE TITLE
socket connect ETIMEDOUT 

### ISSUE THREAD

**Issue by GZWZC** [erictik/midjourney-api#95]
### the code that reproduces this issue or a replay of the bug

cc@ccdeMacBook-Pro midjourney-api-main % npx tsx ./example/imagine-dm.ts

ws this.config.WsBaseUrl, wss://gateway.discord.gg?v=9&encoding=json&compress=gzip-stream
Error: connect ETIMEDOUT 108.160.166.57:443
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Emitted 'error' event on WebSocket instance at:
  websocket.emit('error', err);
            ^

Error
    at null.emitErrorAndClose (/Users/cc/study/shopify/midjourney-api-main/node_modules/ws/lib/websocket.js:1008:13)
    at ClientRequest.<anonymous> (/Users/cc/study/shopify/midjourney-api-main/node_modules/ws/lib/websocket.js:856:5)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '108.160.166.57',
  port: 443
}

### Describe the bug

**Describe the bug**

**Expected behavior**

**Screenshots**

### error log

cc@ccdeMacBook-Pro midjourney-api-main % npx tsx ./example/imagine-dm.ts

ws this.config.WsBaseUrl, wss://gateway.discord.gg?v=9&encoding=json&compress=gzip-stream
Error: connect ETIMEDOUT 108.160.166.57:443
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Emitted 'error' event on WebSocket instance at:
  websocket.emit('error', err);
            ^

Error
    at null.emitErrorAndClose (/Users/cc/study/shopify/midjourney-api-main/node_modules/ws/lib/websocket.js:1008:13)
    at ClientRequest.<anonymous> (/Users/cc/study/shopify/midjourney-api-main/node_modules/ws/lib/websocket.js:856:5)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '108.160.166.57',
  port: 443
}

**Comment by ywachao** [comment]
me too

**Comment by GZWZC** [comment]
The network is relatively poor, a strong vpn is needed
